apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: demo-storage
  hostPath:
    path: /run/desktop/mnt/host/Users/chloehulme/Desktop/Week-9/MappedFolder
